### ISSUE TITLE
Relationship to iterator-hof

### ISSUE THREAD

**Issue by RangerMauve** [tc39/proposal-collection-methods#5]
There's [another proposal](https://github.com/leebyron/ecmascript-iterator-hof) that adds a bunch of utilities for iterators in general.

Are the two proposals complementary, competing, or totally separated?

**Comment by michaelficarra** [comment]
I would also like to see a transducer-style approach explored. For those unfamiliar, transducers allow one to compose higher order operations, then later apply them to some data structure with a way to collect the results. In contrast to typical applications of HOFs, the composed operations will all be applied in a single pass over the data structure. This is like a manual way of getting stream fusion that you get for free in pure FP languages.

There's a pretty popular JS implementation of this called [transducers.js](https://github.com/jlongster/transducers.js) which has more info and examples.
