### ISSUE TITLE
move repo to tc39 org

### ISSUE THREAD

**Issue by gsathya** [tc39/proposal-collection-methods#9]
I don't think I have permissions to do this @Ginden

**Comment by ljharb** [comment]
@Ginden; i've temporarily added you to the tc39-transfer org; you should be able transfer this repo there.

**Comment by Ginden** [comment]
@ljharb @gsathya Transfered to tc39-transfers.

**Comment by Ginden** [comment]
@littledan Can you move this repo too?

**Comment by littledan** [comment]
@Ginden Done, thanks for the ping.
